//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tass___military
{
    using System;
    using System.Collections.Generic;
    
    public partial class alliance_with_duplicates
    {
        public string state_name1 { get; set; }
        public string state_name2 { get; set; }
    }
}
