//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tass___military
{
    using System;
    using System.Collections.Generic;
    
    public partial class military_full
    {
        public string Country { get; set; }
        public double Military_budget__US__BN_ { get; set; }
        public double Main_battle_tanks { get; set; }
        public double Aircraft_carriers { get; set; }
        public double AWS { get; set; }
        public double Cruisers { get; set; }
        public double Destroyers { get; set; }
        public double Frigates { get; set; }
        public double Corvettes { get; set; }
        public double Nuclear_submarines { get; set; }
        public double Non_nuclear_Submarines { get; set; }
        public double Military_aircraft { get; set; }
        public double Attack_helicopters { get; set; }
        public double Nuclear_weapons { get; set; }
        public double Military_satellites { get; set; }
        public double Active_military { get; set; }
        public double Reserve_military { get; set; }
        public double Paramilitary { get; set; }
        public double Total { get; set; }
        public double Per_1000_capita_total_ { get; set; }
        public double Per_1000_capita_active_ { get; set; }
    }
}
